### ISSUE TITLE
Gtk4 is not consistent

### ISSUE THREAD

**Issue by MaxVerevkin** [lollek/Gruvbox-GTK-Theme#1]
Gtk3 is on the left, Gtk4 is on the right:

![image](https://user-images.githubusercontent.com/34583604/159110951-aeaf2353-e99b-44cd-8ea7-8d5f2c708f5c.png)

**Comment by lollek** [comment]
Maybe I should have been a bit more clear about this in the readme, but this is just a personal fork of [Fausto-Korpsvart/Gruvbox-GTK-Theme](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme). It's better if you use that repository instead (and report the issue in that repository).
